name: number_pagination
description: Pagination using number, such as the classic web style pagination.
version: 0.0.3+2
homepage: https://github.com/xpwmaosldk/number_pagination

environment:
  sdk: ">=2.12.0 <3.0.0"
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
